box_name = ENV["TEST_BOX_NAME"] || "me/Win10LTSB_x64"

Vagrant.configure("2") do |config|
  config.vm.box = box_name

	config.vm.synced_folder ".", "/vagrant", type: "rsync"

  config.vm.provision "file", source: "flag.txt", destination: "C:\\Users\\vagrant\\flag.txt"
  config.vm.provision "shell", path: "bootstrap.ps1"
end
